// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.identity().name("owner_id"),
  homePlanetId: __t.u64().name("home_planet_id"),
  resultType: __t.string().name("result_type"),
  lootIron: __t.f64().name("loot_iron"),
  lootPlasma: __t.f64().name("loot_plasma"),
  lootCrystals: __t.f64().name("loot_crystals"),
  completedAt: __t.timestamp().name("completed_at"),
});
