// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  systemId: __t.u32().name("system_id"),
  slotIndex: __t.u32().name("slot_index"),
  orbitalRadius: __t.f64().name("orbital_radius"),
  initialAngle: __t.f64().name("initial_angle"),
  orbitalSpeed: __t.f64().name("orbital_speed"),
  ownerId: __t.option(__t.identity()).name("owner_id"),
  name: __t.option(__t.string()),
  iron: __t.f64(),
  plasma: __t.f64(),
  crystals: __t.f64(),
  lastUpdated: __t.timestamp().name("last_updated"),
});
