// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BuildQueue = __t.object("BuildQueue", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  planetId: __t.u64(),
  buildingType: __t.string(),
  targetLevel: __t.u32(),
});
export type BuildQueue = __Infer<typeof BuildQueue>;

export const Building = __t.object("Building", {
  id: __t.u64(),
  planetId: __t.u64(),
  buildingType: __t.string(),
  level: __t.u32(),
});
export type Building = __Infer<typeof Building>;

export const ExpeditionLog = __t.object("ExpeditionLog", {
  id: __t.u64(),
  ownerId: __t.identity(),
  homePlanetId: __t.u64(),
  resultType: __t.string(),
  lootIron: __t.f64(),
  lootPlasma: __t.f64(),
  lootCrystals: __t.f64(),
  completedAt: __t.timestamp(),
});
export type ExpeditionLog = __Infer<typeof ExpeditionLog>;

export const Fleet = __t.object("Fleet", {
  ownerId: __t.identity(),
  explorerCount: __t.u32(),
});
export type Fleet = __Infer<typeof Fleet>;

export const FleetMission = __t.object("FleetMission", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  ownerId: __t.identity(),
  sourcePlanetId: __t.u64(),
  targetPlanetId: __t.u64(),
});
export type FleetMission = __Infer<typeof FleetMission>;

export const GameConfig = __t.object("GameConfig", {
  id: __t.u32(),
  numSystems: __t.u32(),
  slotsPerSystem: __t.u32(),
  galaxyRadius: __t.f64(),
  initialized: __t.bool(),
});
export type GameConfig = __Infer<typeof GameConfig>;

export const Planet = __t.object("Planet", {
  id: __t.u64(),
  systemId: __t.u32(),
  slotIndex: __t.u32(),
  orbitalRadius: __t.f64(),
  initialAngle: __t.f64(),
  orbitalSpeed: __t.f64(),
  ownerId: __t.option(__t.identity()),
  name: __t.option(__t.string()),
  iron: __t.f64(),
  plasma: __t.f64(),
  crystals: __t.f64(),
  lastUpdated: __t.timestamp(),
});
export type Planet = __Infer<typeof Planet>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  planetId: __t.option(__t.u64()),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const ResourceTick = __t.object("ResourceTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ResourceTick = __Infer<typeof ResourceTick>;

export const ReturnMission = __t.object("ReturnMission", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  ownerId: __t.identity(),
  homePlanetId: __t.u64(),
  resultType: __t.string(),
  lootIron: __t.f64(),
  lootPlasma: __t.f64(),
  lootCrystals: __t.f64(),
});
export type ReturnMission = __Infer<typeof ReturnMission>;

export const SolarSystem = __t.object("SolarSystem", {
  id: __t.u32(),
  systemIndex: __t.u32(),
  orbitalRadius: __t.f64(),
  initialAngle: __t.f64(),
  orbitalSpeed: __t.f64(),
});
export type SolarSystem = __Infer<typeof SolarSystem>;

export const VisitorLog = __t.object("VisitorLog", {
  id: __t.u64(),
  planetOwnerId: __t.identity(),
  visitedPlanetId: __t.u64(),
  visitorIdentity: __t.identity(),
  visitorName: __t.option(__t.string()),
  arrivedAt: __t.timestamp(),
});
export type VisitorLog = __Infer<typeof VisitorLog>;

