// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  planetOwnerId: __t.identity().name("planet_owner_id"),
  visitedPlanetId: __t.u64().name("visited_planet_id"),
  visitorIdentity: __t.identity().name("visitor_identity"),
  visitorName: __t.option(__t.string()).name("visitor_name"),
  arrivedAt: __t.timestamp().name("arrived_at"),
});
