// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuildShipReducer from "../build_ship_reducer";
import CancelBuildReducer from "../cancel_build_reducer";
import DebugGiveResourcesReducer from "../debug_give_resources_reducer";
import SendFleetReducer from "../send_fleet_reducer";
import SetNameReducer from "../set_name_reducer";
import SetPlanetNameReducer from "../set_planet_name_reducer";
import UpgradeBuildingReducer from "../upgrade_building_reducer";

export type BuildShipParams = __Infer<typeof BuildShipReducer>;
export type CancelBuildParams = __Infer<typeof CancelBuildReducer>;
export type DebugGiveResourcesParams = __Infer<typeof DebugGiveResourcesReducer>;
export type SendFleetParams = __Infer<typeof SendFleetReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetPlanetNameParams = __Infer<typeof SetPlanetNameReducer>;
export type UpgradeBuildingParams = __Infer<typeof UpgradeBuildingReducer>;

